/**
 * RISITEX's catalog of system WhatsApp templates — pushed to polyg.in
 * via POST /api/user/add_meta_templet.
 *
 * Naming rules (Meta-enforced): lowercase letters, digits, underscores,
 * ≤512 chars. We use the slug-with-dots → name-with-underscores
 * convention because Meta rejects dots in template names while the slug
 * is more readable in source code.
 *
 * Categories Meta accepts:
 *   - AUTHENTICATION  (single-purpose: deliver an OTP). Lowest latency,
 *                     highest deliverability, but body is constrained
 *                     to a one-time-code template shape.
 *   - UTILITY         (transactional: confirmations, status updates,
 *                     receipts).
 *   - MARKETING       (promotional). We don't seed marketing templates
 *                     by default — they're for the brand's growth team
 *                     to author through the admin UI.
 *
 * Variables: each template lists its variables in order. The position
 * is the {{N}} slot — index 0 is {{1}}.
 */

export type WhatsappComponent =
    | { type: "HEADER"; format?: "TEXT" | "IMAGE" | "VIDEO" | "DOCUMENT"; text?: string; example?: any }
    /** UTILITY/MARKETING body — free-form text. AUTHENTICATION body
     *  uses no text; instead the `add_security_recommendation` flag
     *  asks Meta to auto-append a "Don't share this code" line. */
    | { type: "BODY"; text?: string; example?: { body_text: string[][] }; add_security_recommendation?: boolean }
    /** UTILITY/MARKETING footer — free-form text (max 60). AUTHENTICATION
     *  footer is structured: `code_expiration_minutes` is an integer
     *  1-90 that Meta renders as "This code expires in N minutes". */
    | { type: "FOOTER"; text?: string; code_expiration_minutes?: number }
    | {
          type: "BUTTONS"
          buttons: Array<
              | { type: "QUICK_REPLY"; text: string }
              | { type: "URL"; text: string; url: string }
              | { type: "PHONE_NUMBER"; text: string; phone_number: string }
              /** AUTHENTICATION-only OTP buttons. Meta auto-renders the
               *  button label so `text` is optional. otp_type=COPY_CODE
               *  is the safest and works on every WhatsApp client. */
              | { type: "OTP"; otp_type: "COPY_CODE" | "ONE_TAP" | "ZERO_TAP"; text?: string }
          >
      }

export type WhatsappVariable = {
    /** Snake-case key used by callers, e.g. "first_name" or "otp". */
    key: string
    /** Sample value Meta sees during template-approval review. */
    sample: string
    /** Free-text description for the admin UI. */
    description?: string
    required?: boolean
}

export type DefaultWhatsappTemplate = {
    slug: string
    name: string
    label: string
    description: string
    category: "AUTHENTICATION" | "UTILITY" | "MARKETING"
    language: string
    components: WhatsappComponent[]
    variables: WhatsappVariable[]
}

/**
 * `{{storefront_url}}` resolves at copy/push time from the BrandConfig
 * row. We use the placeholder rather than baking the host so deploying
 * a re-skinned instance only needs a Brand-tab edit, not a re-seed.
 */
const STOREFRONT = "{{storefront_url}}"

export const DEFAULT_WHATSAPP_TEMPLATES: DefaultWhatsappTemplate[] = [
    // ───────── Authentication ───────────────────────────────────────
    // Meta's AUTHENTICATION category is special:
    //   - BODY is auto-generated by Meta as "<code> is your verification
    //     code." — you do NOT write the text. Instead set
    //     `add_security_recommendation: true` so Meta appends "For your
    //     security, do not share this code with anyone."
    //   - FOOTER is a `code_expiration_minutes` integer (1-90) that
    //     Meta renders as "This code expires in N minutes" (localized).
    //     No free-form text allowed.
    //   - BUTTONS must be the OTP type. COPY_CODE works on every
    //     WhatsApp client and is the safest default. Meta auto-renders
    //     the button label.
    //
    // Submitting OTP-style content under UTILITY gets rejected with
    // INCORRECT_CATEGORY because Meta's classifier reroutes anything
    // matching its OTP pattern to the AUTHENTICATION flow.
    //
    // The RISITEX OTP send path remains compatible — it reads the
    // template's `name` and Polygin's send_templet API handles either
    // category transparently.
    {
        slug: "auth.phone_otp_login",
        name: "risitex_phone_otp_login_v1",
        label: "Phone OTP — login",
        description:
            "Sent when a customer requests a one-time code to sign in via /login/phone.",
        category: "AUTHENTICATION",
        language: "en",
        components: [
            { type: "BODY", add_security_recommendation: true },
            { type: "FOOTER", code_expiration_minutes: 10 },
            {
                type: "BUTTONS",
                buttons: [{ type: "OTP", otp_type: "COPY_CODE" }],
            },
        ],
        variables: [
            { key: "otp", sample: "123456", required: true, description: "6-digit one-time code" },
        ],
    },
    {
        slug: "auth.phone_verify_otp",
        name: "risitex_phone_verify_otp_v1",
        label: "Phone OTP — verification",
        description:
            "Sent when a signed-in customer verifies their mobile number from /account/verify-phone.",
        category: "AUTHENTICATION",
        language: "en",
        components: [
            { type: "BODY", add_security_recommendation: true },
            { type: "FOOTER", code_expiration_minutes: 10 },
            {
                type: "BUTTONS",
                buttons: [{ type: "OTP", otp_type: "COPY_CODE" }],
            },
        ],
        variables: [
            { key: "otp", sample: "847291", required: true, description: "6-digit verification code" },
        ],
    },

    // ───────── Account lifecycle ────────────────────────────────────
    {
        slug: "account.welcome",
        name: "risitex_account_welcome_v1",
        label: "Welcome — post-register",
        description:
            "Sent immediately after a fresh customer registers + verifies their phone.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, welcome to {{brand}}! Your account is ready. Tap below to browse our PIX collection.",
                example: { body_text: [["Mira"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "Browse catalogue", url: `${STOREFRONT}/wholesale/catalogue` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
        ],
    },
    {
        slug: "account.password_reset",
        name: "risitex_password_reset_v1",
        label: "Password reset request",
        description:
            "Companion to the password-reset email — sent over WhatsApp when a customer triggers a reset.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, we received a password-reset request for your {{brand}} account. The link is valid for 15 minutes. If you didn't request this, ignore this message.",
                example: { body_text: [["Mira"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "Reset password", url: `${STOREFRONT}/reset-password` },
                ],
            },
        ],
        variables: [{ key: "first_name", sample: "Mira", required: true }],
    },
    // OTP-based password reset (replaces the legacy link-based flow
    // above). Same AUTHENTICATION-category shape as auth.phone_otp_login
    // — a 6-digit OTP delivered with Meta's COPY_CODE button. The
    // password-reset/send route uses this slug when channel=phone.
    {
        slug: "auth.password_reset_otp",
        name: "risitex_password_reset_otp_v1",
        label: "Password reset OTP",
        description:
            "Sent over WhatsApp when a customer triggers an OTP-based password reset (channel=phone on /forgot-password). Reuse the same Meta-approved OTP shape as auth.phone_otp_login.",
        category: "AUTHENTICATION",
        language: "en",
        components: [
            { type: "BODY", add_security_recommendation: true },
            { type: "FOOTER", code_expiration_minutes: 10 },
            {
                type: "BUTTONS",
                buttons: [{ type: "OTP", otp_type: "COPY_CODE" }],
            },
        ],
        variables: [
            { key: "otp", sample: "123456", required: true, description: "6-digit one-time code" },
        ],
    },
    // Tamper-evident notification fired after a successful password
    // change from /account. UTILITY category — a confirmation,
    // not an OTP. Per the May-2026 spec: password changes go via WA + SMS.
    {
        slug: "auth.password_changed",
        name: "risitex_password_changed_v1",
        label: "Password changed",
        description:
            "Sent after a customer changes their password from the account page. Acts as a tamper-evident security notice — if the user didn't initiate, the message tells them to contact support.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, your {{brand}} password was just changed. If this wasn't you, contact support immediately at {{2}}.",
                example: { body_text: [["Mira", "support@risitex.in"]] },
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "support_email", sample: "support@risitex.in", required: true },
        ],
    },

    // ───────── Order lifecycle ──────────────────────────────────────
    // Purchase confirmation — fires when payment is captured for an
    // order. Distinct from `order.placed` because async payment flows
    // (UPI mandate, NACH) settle minutes-to-days after the order is
    // placed; this is the explicit "money received" closure.
    {
        slug: "order.payment_captured",
        name: "risitex_order_payment_captured_v1",
        label: "Order — payment received",
        description:
            "Sent when payment is successfully captured for an order. Confirms the purchase to the customer.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, payment of ₹{{2}} for RISITEX order #{{3}} received. Your order is now in fulfillment.",
                example: { body_text: [["Mira", "1,250", "10234"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "View order", url: `${STOREFRONT}/b2b/orders` },
                ],
            },
            { type: "FOOTER", text: "{{brand}} — {{tagline}}" },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "amount_inr", sample: "1,250", required: true },
            { key: "order_id", sample: "10234", required: true },
        ],
    },
    {
        slug: "order.canceled",
        name: "risitex_order_canceled_v1",
        label: "Order — canceled",
        description:
            "Sent when an order is canceled (by admin, customer, or system). Reason in the body sets expectations for the refund.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, your RISITEX order #{{2}} has been canceled: {{3}}. Any debited amount will be credited back to your wallet within 1 business day.",
                example: {
                    body_text: [["Mira", "10234", "Customer requested"]],
                },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "View order", url: `${STOREFRONT}/b2b/orders` },
                    { type: "URL", text: "Check refund", url: `${STOREFRONT}/b2b/wallet#recent-activity` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "order_id", sample: "10234", required: true },
            {
                key: "reason",
                sample: "Customer requested",
                required: true,
            },
        ],
    },
    {
        slug: "order.placed",
        name: "risitex_order_placed_v1",
        label: "Order placed",
        description:
            "Sent right after checkout; dispatch happens once payment is captured + items are picked.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, your RISITEX order #{{2}} for {{3}} items totalling ₹{{4}} has been placed. We'll notify you when it ships.",
                example: { body_text: [["Mira", "10234", "3", "1,250"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "View order", url: `${STOREFRONT}/b2b/orders` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "order_id", sample: "10234", required: true },
            { key: "item_count", sample: "3", required: true },
            { key: "total_inr", sample: "1,250", required: true },
        ],
    },
    {
        slug: "order.shipped",
        name: "risitex_order_shipped_v1",
        label: "Order — shipped",
        description: "Sent when an order is dispatched by the carrier.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, your RISITEX order #{{2}} was shipped via {{3}}. AWB: {{4}}. Tap below to track.",
                example: {
                    body_text: [["Mira", "10234", "Bluedart", "N12345"]],
                },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "Track shipment", url: "{{tracking_url}}" },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "order_id", sample: "10234", required: true },
            { key: "carrier", sample: "Bluedart", required: true },
            { key: "tracking_number", sample: "N12345", required: true },
            {
                key: "tracking_url",
                sample: "https://www.bluedart.com/tracking?awb=N12345",
                required: true,
            },
        ],
    },
    {
        slug: "order.delivered",
        name: "risitex_order_delivered_v1",
        label: "Order — delivered",
        description: "Sent when an order is marked delivered by the carrier.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, your RISITEX order #{{2}} was delivered. Tap below if anything needs to be exchanged.",
                example: { body_text: [["Mira", "10234"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "View order", url: `${STOREFRONT}/b2b/orders` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "order_id", sample: "10234", required: true },
        ],
    },

    // ───────── Wallet ───────────────────────────────────────────────
    {
        slug: "wallet.credited",
        name: "risitex_wallet_credited_v1",
        label: "Wallet — funds credited",
        description: "Sent when a customer's wallet is credited.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, ₹{{2}} has been credited to your {{brand}} wallet. New balance: ₹{{3}}. Happy shopping!",
                example: { body_text: [["Mira", "500", "2,340"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "View wallet", url: `${STOREFRONT}/b2b/wallet` },
                    { type: "URL", text: "Recent activity", url: `${STOREFRONT}/b2b/wallet#recent-activity` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "amount_inr", sample: "500", required: true },
            { key: "new_balance_inr", sample: "2,340", required: true },
        ],
    },
    {
        slug: "wallet.debited",
        name: "risitex_wallet_debited_v1",
        label: "Wallet — funds debited",
        description: "Sent when a customer's wallet is debited (e.g. for an order).",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, ₹{{2}} debited from your {{brand}} wallet for order #{{3}}. New balance: ₹{{4}}. Track your order on the dashboard.",
                example: { body_text: [["Mira", "1,250", "10234", "1,090"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "Track order", url: `${STOREFRONT}/b2b/orders` },
                    { type: "URL", text: "Recent activity", url: `${STOREFRONT}/b2b/wallet#recent-activity` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "amount_inr", sample: "1,250", required: true },
            { key: "order_id", sample: "10234", required: true },
            { key: "new_balance_inr", sample: "1,090", required: true },
        ],
    },

    // ───────── Wholesale / B2B onboarding ───────────────────────────
    {
        slug: "company.approved",
        name: "risitex_company_approved_v1",
        label: "Wholesale — approved",
        description: "Sent when a wholesale / B2B account application is approved.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, your RISITEX wholesale account is live! Tier: {{2}}. Browse the B2B catalogue at {{brand}} for tier pricing.",
                example: { body_text: [["Mira", "Silver"]] },
            },
            {
                type: "BUTTONS",
                buttons: [
                    { type: "URL", text: "Open catalogue", url: `${STOREFRONT}/wholesale/catalogue` },
                ],
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            { key: "tier_name", sample: "Silver", required: true },
        ],
    },
    {
        slug: "company.rejected",
        name: "risitex_company_rejected_v1",
        label: "Wholesale — rejected",
        description: "Sent when a wholesale / B2B application is not approved.",
        category: "UTILITY",
        language: "en",
        components: [
            {
                type: "BODY",
                text: "Hi {{1}}, we couldn't approve your RISITEX wholesale application this round. Reason: {{2}}. Reply to this message or update your application from your account.",
                example: {
                    body_text: [["Mira", "GSTIN couldn't be verified"]],
                },
            },
        ],
        variables: [
            { key: "first_name", sample: "Mira", required: true },
            {
                key: "reason",
                sample: "GSTIN couldn't be verified",
                required: true,
            },
        ],
    },
]
